Repository Romi904/Durmello, pull requests merged in 2022-10, with the labels that each got.

#2 API
  API
Labels: hacktoberfest_accepted, ACCEPTED

#3 Create easy
  easy
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#1 linkedlist.c
  calculator
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#5 Update Contributors name.txt
  Contributors name.txt
Labels: ACCEPTED

#6 Created Bubble Sort Algorithm in C++
  Bubble Sort Algorithm.cpp
Labels: ACCEPTED

#7 simple game website project in html(index.html)
  index.html
Labels: ACCEPTED, HACKTOBER

#9 Create nQueen.cpp
  nQueen.cpp
Labels: hacktoberfest_accepted, ACCEPTED

#8 Create POlise
  POlise
Labels: good first issue, hacktoberfest_accepted, ACCEPTED, HACKTOBER

#10 Create Dijkstra.c
  Dijkstra.c
Labels: ACCEPTED, HACKTOBER

#11 Add program to check palindrome
  palindrome.py
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#13 Create Armstrong.c
  Armstrong.c
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#14 Update Contributors name.txt
  Contributors name.txt
Labels: good first issue, hacktoberfest_accepted, ACCEPTED, HACKTOBER

#15 untitled.ipynb
  Untitled3.ipynb
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#16 Create KMP.cpp
  KMP.cpp
Labels: good first issue, hacktoberfest_accepted, ACCEPTED, HACKTOBER

#18 Update Contributors name.txt
  Contributors name.txt
Labels: hacktoberfest_accepted, ACCEPTED

#19 Update Contributors name.txt
  Contributors name.txt
Labels: good first issue, hacktoberfest_accepted, ACCEPTED, HACKTOBER

#20 Create Selection_Sort.c
  Selection_Sort.c
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#31 Java program on Merge Sort Algorithm
  Merge Sort Algorithm
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#30 snake game
  snakegame.py
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#26 aditya ajay knapsack problems
  .DS_Store
  Knapsack-problems/_1a_01knapsack.cpp
  Knapsack-problems/_1b_tabulation.cpp
  Knapsack-problems/_1c_spaceOpti.cpp
  Knapsack-problems/_2a _ minCoins.cpp
  Knapsack-problems/_2b_tabulation.cpp
  Knapsack-problems/_2c_spaceOpti.cpp
  Knapsack-problems/_3a_coinChange.cpp
  Knapsack-problems/_3b_tabulation.cpp
  Knapsack-problems/_3c_spaceopti.cpp
  Knapsack-problems/_4a_unboundedKnapsack.cpp
  Knapsack-problems/_4b_tabulate.cpp
  Knapsack-problems/_4c_spaceOpti.cpp
  Knapsack-problems/_5a_rodCutting.cpp
  Knapsack-problems/_5b_table.cpp
  Knapsack-problems/_5c_spaceopti.cpp
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#25 backtracking Problems
  Backtracking/MColoringProblem.cpp
  Backtracking/NQueenProblem.cpp
  Backtracking/ratInAMaze.cpp
  Backtracking/sodukoSolver.cpp
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#24 283. Move Zeroes
  Move_Zeroes.py
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#23 Create change_format.py
  change_format.py
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#22 Hangman Game using Python
  Hangman Game using Python.py
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#33 Create Bubblesort.cpp
  Bubblesort.cpp
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#35 Create 22. Generate Parentheses.java
  22. Generate Parentheses.java
Labels: good first issue, hacktoberfest_accepted, ACCEPTED, HACKTOBER

#36 Create leetcode804.cpp
  leetcode804.cpp
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#37 secretor.py
  secretor.py
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#38 Update Contributors name.txt
  Contributors name.txt
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#39 Create games.js
  red-rect-game/games.js
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#40 Update secretor.py
  secretor.py
Labels: hacktoberfest_accepted, ACCEPTED, HACKTOBER

#42 Update Contributors name.txt
  Contributors name.txt
Labels: ACCEPTED

#43 Created Solution For Magnet Puzzle
  Backtracking/Magnet Puzzle
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#44 Create BubbleSort.c
  BubbleSort.c
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#45 Find Roots of a Quadratic Equation
  Roots of a Quadratic Equation
Labels: hacktoberfest-accepted, ACCEPTED

#48 ASCII value of a character
  ASCII value of a character
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#49 Swap two numbers using temporary variable
  Swap two numbers using temporary variable
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#50 Hacktoberfest-2022
  Contributors name.txt
  Tic-Tac-Toe Game/Readme.md
  Tic-Tac-Toe Game/Tic-Tac-Toe 03-10-2022 12_46_04.png
  Tic-Tac-Toe Game/tic_tac_toe.py
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#51 Add files via upload
  stone_paper_sessior.py
  tempCodeRunnerFile.py
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#52 Added a few cpp algos
  Cpp/3-sum.cpp
  Cpp/Bank management.cpp
  Cpp/Bloom_filter.cpp
  Cpp/C++ programs
  Cpp/CheckStringPalindrome.cpp
  Cpp/Fibonacci.cpp
  Cpp/FloodFill.cpp
  Cpp/Graph/BFSByMatrix.cpp
  Cpp/Graph/DFSbyMatrixAndRecursion.cpp
  Cpp/Graph/GraphRepresentation.cpp
  Cpp/Graph/shortestpath_BFS.cpp
  Cpp/Graph/tsort.cpp
  Cpp/Greedy/134. Gas Station.cpp
  Cpp/Greedy/1561. Max_Coins_You_Can_Get.cpp
  Cpp/Greedy/1642. Furthest_Building_You_Can_Reach.cpp
  Cpp/HashTable.cpp
  Cpp/Hotel Management.cpp
  Cpp/Kadane’s algorithm.cpp
  Cpp/Longest Valid Parentheses leetcode.txt
  Cpp/Maximum and minimum of an array using minimum number of comparisons.cpp
  Cpp/N-QUEEN.cpp
  Cpp/Primes_Algorithm.cpp
  Cpp/Regular Expression Matching.cpp
  Cpp/Replace_pi_with_3.14.cpp
  Cpp/SQUARE_ROOT.CPP
  Cpp/SieveOfEratosthenes.cpp
  Cpp/Smallest Missing Prime Number.cpp
  Cpp/Trap.cpp
  Cpp/array_sort_or_not.cpp
  Cpp/arraydisplay.cpp
  Cpp/binary_search.cpp
  Cpp/brute force example/BuyAShovel.cpp
  Cpp/brute force example/DoNotBeDistracted.cpp
  Cpp/brute force example/SpyDetected.cpp
  Cpp/dijkastra.cpp
  Cpp/friendFunction.cpp
  Cpp/get_ip_addreess.cpp
  Cpp/heapSort.cpp
  Cpp/kruskals_minimumSpanningTree.cpp
  Cpp/largeElement_in_Array.cpp
  Cpp/linkedlist/Linked_list_push_back_front_pop_back_front.cpp
  Cpp/linkedlist/add2num.cpp
  Cpp/linkedlist/insertioninlinkedlist.cpp
  Cpp/linkedlist/intersectlist.cpp
  Cpp/linkedlist/listCycle.cpp
  Cpp/linkedlist/merge2list.cpp
  Cpp/linkedlist/middlelist.cpp
  Cpp/linkedlist/removefromend.cpp
  Cpp/linkedlist/reverselist.cpp
  Cpp/longest_consecutive_subsequence.cpp
  Cpp/matrix product.cpp
  Cpp/subset_sum.cpp
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#54 Online DiceGame
  Dice_eGame/index.html
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#55 sompal.c
  sompal.c
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#56 Fibonacci Series in C without recursion
  Fibonacci
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#57 Create Prime Number
  Prime Number
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#58 Create Factorial
  Factorial
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#59 Create Matrix Multiply
  Matrix Multiply
Labels: ACCEPTED, HACKTOBER, Modification_Nedded

#60 CSS code
  Dice_eGame/styles.css
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#61 Javascript code
  Dice_eGame/dice.js
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#62 Added-my-Pig-Game-project
  Pig-Game/dice-1.png
  Pig-Game/dice-2.png
  Pig-Game/dice-3.png
  Pig-Game/dice-4.png
  Pig-Game/dice-5.png
  Pig-Game/dice-6.png
  Pig-Game/index.html
  Pig-Game/script.js
  Pig-Game/style.css
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#63 add 2d game html file
  Contributors name.txt
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#65 Added some more sorting algos
  Cpp/BucketSort.c
  Cpp/CormensQuickSort.c
  Cpp/CountingSort.c
  Cpp/HoaresQuickSort.c
  Cpp/MergeSort.c
  Cpp/RadixSort.c
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#68 QR CODE GENERATOR USING PYTHON
  QR Code Generator.py
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#69 Added Solutions
  DynamicProgramming/HouseRobberII.java
  DynamicProgramming/LongestCommonSubsequence.java
  DynamicProgramming/LongestCommonSubstring.java
  DynamicProgramming/MinimumSwapsMakeSequencesIncreasing.java
Labels: good first issue, hacktoberfest-accepted, ACCEPTED, HACKTOBER

#70 Create KruskalAlgo.cpp
  KruskalAlgo.cpp
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#73 Create nQueen.java
  Java/nQueen.java
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#75 Create FloydWarshal.cpp
  FloydWarshal.cpp
Labels: ACCEPTED

#77 Add files via upload
  Cpp/eidtdistance.cpp
Labels: ACCEPTED

#76 Josephus Problem Using Recursion
  Cpp/Josephus_problem_using_recursion.cpp
Labels: hacktoberfest-accepted, ACCEPTED

#79 Create WriteFile.java
  Java/WriteFile.java
Labels: hacktoberfest-accepted, ACCEPTED

#81 Added solutions to a few more DP problems.
  DynamicProgramming/CoinChange.cpp
  DynamicProgramming/EditDistance.cpp
Labels: good first issue, hacktoberfest-accepted, ACCEPTED, HACKTOBER

#46 Created Pig game using html,css,javascript
  Pig game/html/index.html
  Pig game/javascipt/app.js
  Pig game/style.css
Labels: hacktoberfest-accepted, ACCEPTED

#83 Added Sudoku Solver Code on Java
  Java/Sudoku Solver.java
Labels: hacktoberfest-accepted, ACCEPTED

#86 added_stacks_push_and_pop_program
  stacks_push_and_pop.c
Labels: good first issue, hacktoberfest-accepted, ACCEPTED, HACKTOBER

#95 Added Number Guessing Game
  Number-Guessing-Game/index.html
  Number-Guessing-Game/script.js
  Number-Guessing-Game/style.css
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#96 Create countMaxOfZeroesOrOnes
  countMaxOfZeroesOrOnes
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#99 Create replace lowercase characters with uppercase
  replaceLowerAndUpper
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#101 Important question of Trie
  Trie/DesignAddandSearchWords.cpp
  Trie/PalindromePairs.cpp
  Trie/PrintAnagramsTogether.cpp
  Trie/WordBreakII.cpp
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#100 added tipCahculator
  TipCalculator/calculator.html
  TipCalculator/script.js
  TipCalculator/style.css
Labels: good first issue, hacktoberfest-accepted, ACCEPTED, HACKTOBER

#103 added coingamewinner.java file
  Java/coingamewinner.java
Labels: hacktoberfest-accepted, ACCEPTED, HACKTOBER

#105 Factorial of large numbers,cpp
  Cpp/Factorialoflargenumbers.cpp
Labels: enhancement, hacktoberfest-accepted, ACCEPTED, HACKTOBER

#108 Add Longest_Alternating_Subsequence
  DynamicProgramming/Longest_Alternating_Subsequence.cpp
Labels: good first issue, ACCEPTED

#98 Happy Number problem code added
  Java/HappyNumber.java
Labels: ACCEPTED, BASICS

#112 C++ ALgorithms
  C++/GetMax.cpp
  C++/Issubsequence.cpp
  C++/Testing.txt
  C++/generate_parenthesis.cpp
  C++/good_pair.cpp
  C++/h_index.cpp
  C++/interleavingStrings.cpp
  C++/interval_list.cpp
  C++/k_missing.cpp
  C++/majority.cpp
  C++/max_consec_one.cpp
  C++/merge_sort_arr.cpp
  C++/minimum_depth.cpp
  C++/monotonic_arr.cpp
  C++/number_1_bits.cpp
  C++/permutations.cpp
  C++/permutations_2.cpp
  C++/plus_one.cpp
  C++/product_arr_self.cpp
  C++/remove_invalid_parent.cpp
  C++/reverse_bits.cpp
  C++/shifts_arr.cpp
  C++/single_number.cpp
  C++/sort-arr_parity.cpp
  C++/sort_arr_freq.cpp
  C++/subsets.cpp
  C++/sum_1d_arr.cpp
  C++/sum_xor.cpp
  C++/target_arr.cpp
  C++/validBST.cpp
  C++/word_pattern.cpp
Labels: hacktoberfest-accepted, ACCEPTED

#121 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted, ACCEPTED

#118 Added a face_detection algorithm.
  face_detection.py
Labels: hacktoberfest-accepted, ACCEPTED

#125 Project uses the efficient way to embed YouTube videos in a webpage.
  .DS_Store
  CONTRIBUTING.md
  Efficient-Youtube-Embed/.gitattributes
  Efficient-Youtube-Embed/css/style.css
  Efficient-Youtube-Embed/css/youtube-player.css
  Efficient-Youtube-Embed/index.html
  Efficient-Youtube-Embed/resources/brand-logo.png
  Efficient-Youtube-Embed/resources/fast-shipping.png
  Efficient-Youtube-Embed/resources/favicon.ico
  Efficient-Youtube-Embed/resources/premium.png
  Efficient-Youtube-Embed/resources/quality-assurance.png
  Efficient-Youtube-Embed/resources/trumpet.png
  Efficient-Youtube-Embed/resources/youtube-play.png
Labels: hacktoberfest-accepted, ACCEPTED

#135 Added Snake and apple python game
  snakeandapple.py
Labels: hacktoberfest-accepted, ACCEPTED

#138 Create sendEmail
  sendEmail.py
Labels: ACCEPTED

#143 Added Space invader game
  5512626.jpg
  bullet.png
  main.py
  spaceship.png
  ufo.png
Labels: hacktoberfest-accepted, ACCEPTED

#146 added BMI calculator
  BMICalculator/README.md
  BMICalculator/Readme_Image/photo_2022-10-06_11-49-34.jpg
  BMICalculator/Readme_Image/photo_2022-10-06_11-49-37.jpg
  BMICalculator/Readme_Image/photo_2022-10-06_11-49-41.jpg
  BMICalculator/Readme_Image/photo_2022-10-06_11-49-44.jpg
  BMICalculator/Readme_Image/photo_2022-10-06_11-49-47.jpg
  BMICalculator/app/build.gradle
  BMICalculator/app/proguard-rules.pro
  BMICalculator/app/s.c
  BMICalculator/app/src/androidTest/java/com/example/bmicalculator/ExampleInstrumentedTest.kt
  BMICalculator/app/src/main/AndroidManifest.xml
  BMICalculator/app/src/main/ic_launcher-playstore.png
  BMICalculator/app/src/main/java/com/example/bmicalculator/MainActivity.kt
  BMICalculator/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  BMICalculator/app/src/main/res/drawable/bmi_logo.png
  BMICalculator/app/src/main/res/drawable/healthyweight.png
  BMICalculator/app/src/main/res/drawable/ic_launcher_background.xml
  BMICalculator/app/src/main/res/drawable/obesweight.png
  BMICalculator/app/src/main/res/drawable/overweight.png
  BMICalculator/app/src/main/res/drawable/underweight.png
  BMICalculator/app/src/main/res/layout/activity_main.xml
  BMICalculator/app/src/main/res/mipmap-hdpi/ic_launcher.png
  BMICalculator/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  BMICalculator/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  BMICalculator/app/src/main/res/mipmap-mdpi/ic_launcher.png
  BMICalculator/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  BMICalculator/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  BMICalculator/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  BMICalculator/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  BMICalculator/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  BMICalculator/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  BMICalculator/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  BMICalculator/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  BMICalculator/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  BMICalculator/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  BMICalculator/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  BMICalculator/app/src/main/res/values-night/themes.xml
  BMICalculator/app/src/main/res/values/colors.xml
  BMICalculator/app/src/main/res/values/ic_launcher_background.xml
  BMICalculator/app/src/main/res/values/strings.xml
  BMICalculator/app/src/main/res/values/themes.xml
  BMICalculator/app/src/main/res/xml/backup_rules.xml
  BMICalculator/app/src/main/res/xml/data_extraction_rules.xml
  BMICalculator/app/src/test/java/com/example/bmicalculator/ExampleUnitTest.kt
  BMICalculator/build.gradle
  BMICalculator/gradle.properties
  BMICalculator/gradle/wrapper/gradle-wrapper.jar
  BMICalculator/gradle/wrapper/gradle-wrapper.properties
  BMICalculator/gradlew
  BMICalculator/gradlew.bat
  BMICalculator/local.properties
  BMICalculator/settings.gradle
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, ACCEPTED

#154 A 3D audio visualiser using ThreeJS for the web.
  3d_audio_visualizer/README.md
  3d_audio_visualizer/index.html
  3d_audio_visualizer/package-lock.json
  3d_audio_visualizer/package.json
  3d_audio_visualizer/script.js
  3d_audio_visualizer/style.css
Labels: hacktoberfest-accepted

#150 [added] project : fruit ninja using python
  BMICalculator/.gradle/7.3.3/checksums/checksums.lock
  BMICalculator/.gradle/7.3.3/fileChanges/last-build.bin
  BMICalculator/.gradle/7.3.3/fileHashes/fileHashes.lock
  BMICalculator/.gradle/7.3.3/gc.properties
  BMICalculator/.gradle/vcs-1/gc.properties
  CONTRIBUTING.md
  Fruit Ninja using Python/back.jpg
  Fruit Ninja using Python/comic.ttf
  Fruit Ninja using Python/fruit_ninja.py
  Fruit Ninja using Python/images/backgound.jpg
  Fruit Ninja using Python/images/bomb.png
  Fruit Ninja using Python/images/explosion.png
  Fruit Ninja using Python/images/game_over.png
  Fruit Ninja using Python/images/guava.png
  Fruit Ninja using Python/images/half_guava.png
  Fruit Ninja using Python/images/half_melon.png
  Fruit Ninja using Python/images/half_orange.png
  Fruit Ninja using Python/images/half_pomegranate.png
  Fruit Ninja using Python/images/melon.png
  Fruit Ninja using Python/images/orange.png
  Fruit Ninja using Python/images/pomegranate.png
  Fruit Ninja using Python/images/red_lives.png
  Fruit Ninja using Python/images/white_lives.png
Labels: good first issue, hacktoberfest-accepted

#161 added the game
  guess-the colour-game/main.py
Labels: hacktoberfest-accepted

#152 mad libs game in python programming
  madlibs_game.py
Labels: hacktoberfest-accepted

#169 adding countries_trivia_game
  countries_trivia_game/README.md
  countries_trivia_game/african_countries.csv
  countries_trivia_game/countries_trivia.py
Labels: hacktoberfest-accepted, ACCEPTED

#159 Added Automatic Birthday Wisher Python Project
  Automatic Birthday Wisher Using Python/data.xlsx
  Automatic Birthday Wisher Using Python/main.py
Labels: hacktoberfest-accepted

#170 Updated CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, ACCEPTED

#173 Create Countdown Timer Using PHP & Resolve conflicts
  CONTRIBUTING.md
  countdownTimer.php
Labels: hacktoberfest-accepted

#172 Added cycling/running scheduler map JS project
  Workout planner/icon.png
  Workout planner/index.html
  Workout planner/logo.png
  Workout planner/script.js
  Workout planner/style.css
Labels: hacktoberfest-accepted

#174 Added Game Project
  CONTRIBUTING.md
  Number Guessing Game/index.html
  Number Guessing Game/script.js
  Number Guessing Game/style.css
  Rolling The Dice Game/dice-1.png
  Rolling The Dice Game/dice-2.png
  Rolling The Dice Game/dice-3.png
  Rolling The Dice Game/dice-4.png
  Rolling The Dice Game/dice-5.png
  Rolling The Dice Game/dice-6.png
  Rolling The Dice Game/index.html
  Rolling The Dice Game/script.js
  Rolling The Dice Game/style.css
Labels: hacktoberfest-accepted

#175 Added files for the AVL Tree
  CONTRIBUTING.md
  Simon-Game/game.js
  Simon-Game/index.html
  Simon-Game/simon_ss.png
  Simon-Game/sounds/blue.mp3
  Simon-Game/sounds/green.mp3
  Simon-Game/sounds/red.mp3
  Simon-Game/sounds/wrong.mp3
  Simon-Game/sounds/yellow.mp3
  Simon-Game/styles.css
  Simple-Weather-App/README.md
  Simple-Weather-App/bg.jpg
  Simple-Weather-App/favicon.ico
  Simple-Weather-App/index.html
  Simple-Weather-App/main.css
  Simple-Weather-App/main.js
Labels: hacktoberfest-accepted, ACCEPTED, BASICS

#177 Update Contributing.md
  CONTRIBUTING.md
Labels: Under-Review

#182 Hangman_added
  hangman_game/idetniftthe_word.py
  hangman_game/words.py
Labels: hacktoberfest-accepted, ACCEPTED

#168 Added Java Program
  CONTRIBUTING.md
  Java/Frequency.java
Labels: hacktoberfest-accepted

#194 Added Quote of the Day Generator Project
  Quote of Day Project/README.md
  Quote of Day Project/index.html
  Quote of Day Project/quotes generator javascript project pic.png
  Quote of Day Project/quotes.css
  Quote of Day Project/quotes.js
Labels: hacktoberfest-accepted

#202 Updated CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#197 Create Cards_game.py
  Cards_game.py
Labels: hacktoberfest-accepted

#196 Create Spinner.py
  Spinner.py
Labels: hacktoberfest-accepted

#200 added wordle game
  Wordle/dictionary.json
  Wordle/index.html
  Wordle/style.css
  Wordle/targetWords.json
  Wordle/wordle.js
  Wordle/wordle.png
Labels: hacktoberfest-accepted

#204 Quiz App
  Quiz_app/.gitignore
  Quiz_app/README.md
  Quiz_app/package-lock.json
  Quiz_app/package.json
  Quiz_app/public/favicon.ico
  Quiz_app/public/index.html
  Quiz_app/public/logo192.png
  Quiz_app/public/logo512.png
  Quiz_app/public/manifest.json
  Quiz_app/public/robots.txt
  Quiz_app/src/App.css
  Quiz_app/src/App.jsx
  Quiz_app/src/App.test.js
  Quiz_app/src/components/Button.jsx
  Quiz_app/src/components/Header.jsx
  Quiz_app/src/components/Home.jsx
  Quiz_app/src/components/button.css
  Quiz_app/src/components/header.css
  Quiz_app/src/components/home.css
  Quiz_app/src/index.css
  Quiz_app/src/index.js
  Quiz_app/src/logo.svg
  Quiz_app/src/reportWebVitals.js
  Quiz_app/src/setupTests.js
Labels: hacktoberfest-accepted

#207 library management system
  Library management system/Library management system.cpp
Labels: hacktoberfest-accepted
